window.TAMARA_DATA = [
  {name:'Kimberly Bryant', group:'black', role:'Founder & STEM education leader', field:'STEM Education', founder:true, executive:true, visibility:86, technical:75, leadership:88, ecosystem:94, highlight:'Founder of Black Girls CODE; a major voice in expanding access to technology education.'},
  {name:'Joy Buolamwini', group:'black', role:'AI researcher & founder', field:'Responsible AI', founder:true, executive:true, visibility:95, technical:94, leadership:86, ecosystem:91, highlight:'Known for influential work on algorithmic bias and accountability in artificial intelligence.'},
  {name:'Timnit Gebru', group:'black', role:'AI researcher & founder', field:'AI Research', founder:true, executive:true, visibility:93, technical:96, leadership:89, ecosystem:90, highlight:'Prominent AI researcher whose work centers on ethics, data and the social impact of machine learning.'},
  {name:'Stacy Brown-Philpot', group:'black', role:'Technology executive & investor', field:'Technology Leadership', founder:false, executive:true, visibility:85, technical:78, leadership:96, ecosystem:92, highlight:'Technology executive and investor recognized for scaling high-growth technology organizations.'},
  {name:'Shellye Archambeau', group:'black', role:'Technology CEO & board leader', field:'Enterprise Technology', founder:false, executive:true, visibility:84, technical:72, leadership:97, ecosystem:95, highlight:'Longtime enterprise technology executive, CEO and public-company board leader.'},
  {name:'Lisa Gelobter', group:'black', role:'Technologist & founder', field:'Digital Media', founder:true, executive:true, visibility:82, technical:92, leadership:87, ecosystem:88, highlight:'Engineer and entrepreneur with a career spanning digital media, animation and inclusive technology.'},
  {name:'Arlan Hamilton', group:'black', role:'Venture capitalist & founder', field:'Venture Capital', founder:true, executive:true, visibility:91, technical:62, leadership:90, ecosystem:98, highlight:'Founder and investor known for backing underestimated founders in the startup ecosystem.'},
  {name:'Anne-Marie Imafidon', group:'black', role:'Technologist & social entrepreneur', field:'STEM Advocacy', founder:true, executive:true, visibility:88, technical:85, leadership:90, ecosystem:93, highlight:'Technology leader and social entrepreneur focused on increasing participation of women and girls in STEM.'},
  {name:'Lisa Su', group:'other', role:'Semiconductor executive', field:'Semiconductors', founder:false, executive:true, visibility:96, technical:98, leadership:99, ecosystem:94, highlight:'Widely recognized semiconductor executive with deep technical and business leadership.'},
  {name:'Fei-Fei Li', group:'other', role:'AI scientist & academic leader', field:'Artificial Intelligence', founder:true, executive:true, visibility:97, technical:99, leadership:92, ecosystem:97, highlight:'AI scientist and academic leader known for foundational work in computer vision and human-centered AI.'},
  {name:'Safra Catz', group:'other', role:'Enterprise technology executive', field:'Enterprise Software', founder:false, executive:true, visibility:89, technical:72, leadership:98, ecosystem:93, highlight:'Longtime enterprise technology executive with global business leadership experience.'},
  {name:'Ginni Rometty', group:'other', role:'Former technology CEO & investor', field:'Enterprise Technology', founder:false, executive:true, visibility:92, technical:80, leadership:98, ecosystem:96, highlight:'Former global technology CEO known for enterprise transformation, cloud and AI strategy.'},
  {name:'Sheryl Sandberg', group:'other', role:'Technology executive & founder', field:'Digital Platforms', founder:true, executive:true, visibility:97, technical:68, leadership:95, ecosystem:99, highlight:'Technology executive, author and founder with major influence across digital platforms and leadership.'},
  {name:'Marissa Mayer', group:'other', role:'Engineer, executive & founder', field:'Consumer Technology', founder:true, executive:true, visibility:92, technical:91, leadership:88, ecosystem:91, highlight:'Engineer and technology executive known for leadership across major consumer internet products.'},
  {name:'Whitney Wolfe Herd', group:'other', role:'Technology founder & executive', field:'Consumer Platforms', founder:true, executive:true, visibility:90, technical:70, leadership:91, ecosystem:93, highlight:'Technology founder recognized for building and scaling a major consumer social platform.'},
  {name:'Susan Wojcicki', group:'other', role:'Technology executive', field:'Digital Media', founder:false, executive:true, visibility:96, technical:76, leadership:97, ecosystem:98, highlight:'Influential technology executive whose career shaped digital advertising and online video.'}
];
